name: Vault Access Workflow

on:
  push:
    branches:
      - main

jobs:
  access-vault:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Vault CLI
        run: |
          # Descargar y extraer la CLI de Vault
          wget https://releases.hashicorp.com/vault/1.7.5/vault_1.7.5_linux_amd64.zip
          unzip vault_1.7.5_linux_amd64.zip

          # Mover la CLI de Vault al directorio de binarios
          sudo mv vault /usr/local/bin/
          
      - name: Set up Vault token
        env:
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          echo "$VAULT_TOKEN" > ~/.vault-token
          chmod 600 ~/.vault-token
          
      - name: Access Vault
        run: |
          # Ejemplo: Obtener el estado del sistema de Vault
          vault status
          
      - name: Verify Vault Connection
        run: |
          # Verificar si la conexión fue exitosa
          if [ $? -eq 0 ]; then
            echo "La conexión a Vault fue exitosa"
          else
            echo "Hubo un error al conectar con Vault"
            exit 1
          fi
